# Generated by Django 4.1 on 2025-02-04 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ingrediente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("estoque_min", models.FloatField()),
                ("estoque_atual", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("categoria", models.CharField(max_length=100)),
                ("preco_unitario", models.FloatField()),
                ("quantidade_estoque", models.FloatField()),
                ("validade", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="ProdutoIngrediente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.FloatField()),
                (
                    "ingrediente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Core.ingrediente",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Core.produto"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Receita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "ingredientes",
                    models.ManyToManyField(
                        related_name="receitas",
                        through="Core.ProdutoIngrediente",
                        to="Core.ingrediente",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="produtoingrediente",
            name="receita",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Core.receita"
            ),
        ),
    ]
