# Generated by Django 4.1 on 2025-02-04 22:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingrediente",
            name="descricao",
            field=models.CharField(default="0", max_length=200),
        ),
        migrations.AddField(
            model_name="ingrediente",
            name="unidade_medida",
            field=models.CharField(default="0", max_length=20),
        ),
    ]
