# Generated by Django 4.1 on 2025-02-05 22:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Core", "0002_ingrediente_descricao_ingrediente_unidade_medida"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produto",
            name="categoria",
        ),
        migrations.RemoveField(
            model_name="produto",
            name="validade",
        ),
        migrations.AddField(
            model_name="produto",
            name="min_estoque",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
