# Generated by Django 4.1 on 2025-02-05 22:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Core", "0003_remove_produto_categoria_remove_produto_validade_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="min_estoque",
            field=models.FloatField(default=0),
        ),
    ]
