# Generated by Django 4.1 on 2025-02-05 23:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Core", "0004_alter_produto_min_estoque"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produtoingrediente",
            name="receita",
        ),
        migrations.DeleteModel(
            name="Receita",
        ),
    ]
