# Generated by Django 4.1 on 2025-02-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Core", "0005_remove_produtoingrediente_receita_delete_receita"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ingrediente",
            name="descricao",
        ),
        migrations.AddField(
            model_name="ingrediente",
            name="preco",
            field=models.FloatField(default=0),
        ),
    ]
