# Generated by Django 4.1 on 2025-02-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Core", "0006_remove_ingrediente_descricao_ingrediente_preco"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingrediente",
            name="unidade_medida",
            field=models.CharField(default="Gramas", max_length=20),
        ),
    ]
